Sick new options menu
seongyher/BrackeysJam2024-01 pull request #9
Opened 2024-02-14 08:24 UTC by o-x-y-z-o-n-e

2024-02-14 14:54 UTC, ThisIsDioni approved these changes
Nice job!

2024-02-14 14:54 UTC, ThisIsDioni approved these changes

2024-02-16 02:26 UTC, SabrinaTheCookie requested changes
1. Attach UI to Audio Manager so sliders do something. Check the old options panel for how to do this.
2.  Delete old Options panel (**And** prefab).
3. Have sliders start at 0.9f, or sync them with AudioManager. e.g. OnValidate() changes the slider's values to AudioManager's.

2024-02-16 12:43 UTC, SabrinaTheCookie approved these changes
Freakin sick

2024-02-16 12:43 UTC, merged